
version: 1.0
provider:
    name: openfaas
    gateway: http://serverless.siat.ac.cn:31112

functions:
    
    llama-7b-wholemod-llama-7b-whole:
        namespace: cdgp
        lang: python3-http
        handler: ./llama-7b-wholemod
        image: k.harbor.siat.ac.cn/openfaas/cdgp-llama-7b-wholemod-llama-7b-whole:1.0.1.qitian
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 7000m
            memory: 64Gi
        environment:
            read_timeout: "10.0s"
            write_timeout: "10.0s"
            exec_timeout: "10.0s"
            debug: "false"
            infer_device: "cuda"
    