
version: 1.0
provider:
    name: openfaas
    gateway: http://serverless.siat.ac.cn:31112

functions:
    
    whisper-large-v2-wholemod-whisper-large-v2-whole:
        namespace: cdgp
        lang: python3-http
        handler: ./whisper-large-v2-wholemod
        image: k.harbor.siat.ac.cn/openfaas/cdgp-whisper-large-v2-wholemod-whisper-large-v2-whole:1.0.1.qitian
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 2000m
            memory: 64Gi
        environment:
            read_timeout: "10.0s"
            write_timeout: "10.0s"
            exec_timeout: "10.0s"
            debug: "false"
            infer_device: "cuda"
    