
version: 1.0
provider:
    name: openfaas
    gateway: http://serverless.siat.ac.cn:31112

functions:
    
    wideresnet-9b-submod-2-me-3:
        namespace: cdgp
        lang: python3-http
        handler: ./wideresnet-9b-submod-2
        image: k.harbor.siat.ac.cn/openfaas/cdgp-wideresnet-9b-submod-2-me-3:1.0.1.qitian
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 6000m
            memory: 64Gi
        environment:
            read_timeout: "3.33s"
            write_timeout: "3.33s"
            exec_timeout: "3.33s"
            debug: "false"
            infer_device: "cuda"
    
    wideresnet-9b-submod-1-me-3:
        namespace: cdgp
        lang: python3-http
        handler: ./wideresnet-9b-submod-1
        image: k.harbor.siat.ac.cn/openfaas/cdgp-wideresnet-9b-submod-1-me-3:1.0.1.qitian
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 3000m
            memory: 64Gi
        environment:
            read_timeout: "6.67s"
            write_timeout: "6.67s"
            exec_timeout: "6.67s"
            debug: "false"
            infer_device: "cuda"
    
    wideresnet-9b-submod-0-me-3:
        namespace: cdgp
        lang: python3-http
        handler: ./wideresnet-9b-submod-0
        image: k.harbor.siat.ac.cn/openfaas/cdgp-wideresnet-9b-submod-0-me-3:1.0.1.qitian
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 1000m
            memory: 64Gi
        environment:
            read_timeout: "10.0s"
            write_timeout: "10.0s"
            exec_timeout: "10.0s"
            debug: "false"
            infer_device: "cuda"
    